% Fig. 1: One-parameter family of limit cycles generated by the Hodgkin-
% Huxley equations for I over [10,150]

C = 1; 
gK = 36; EK = -12;
gNa = 120; ENa = 120;
gL = 0.3; EL = 10.6;

I  = 10: 10: 150;
n = length(I);
T0 = zeros(1,n);

initials1 = [0,0.582483641907492,0.048145598184594,0.193952946600929]; % a tentative initial condition
t0 = 0; tF = 1000; dt = 0.01; tspan = t0:0.01:100;

for k = 1:n
[T1,P1] = ode45(@HH_model,[t0:dt:tF],initials1,[],C,I(k),gK,EK,gNa,ENa,gL,EL);
initials2 = P1(end,:);
options = odeset('Events',@HH_event3);
[~,~,~,initials2,~] = ode45(@HH_model,[0 tF],initials2,options,C,I(k),gK,EK,gNa,ENa,gL,EL);
[~,~,T_temp,~,~] = ode45(@HH_model,[0 tF],initials2,options,C,I(k),gK,EK,gNa,ENa,gL,EL);
T0(k) = T_temp(end);  % period
j = round(T0(k)/dt);
[T2,P2] = ode45(@HH_model,tspan,initials2,[],C,I(k),gK,EK,gNa,ENa,gL,EL);
V = P2(:,1); n = P2(:,2);

figure(2)
subplot(1,2,1)  %(I,t,V)
plot3(I(k)*ones(length(tspan),1),T2,V,'-','LineWidth',2)
hold on
xlabel('I (pA)'); ylabel('t (msec)'); zlabel('V (mV)')
grid on
set(gca,'xdir','reverse')
subplot(1,2,2)  %(V,n,I)
plot3(V(1:j),n(1:j),I(k)*ones(j,1),'+','MarkerSize',4)
hold on
xlabel('V (mV)'); ylabel('n'); zlabel('t (msec)');
grid on

end